# Generated by Django 6.0.7 on 2026-07-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0002_encomenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='encomenda',
            options={'verbose_name_plural': 'Encomendas'},
        ),
    ]
